[package]
name = "examples-anvil"
version = "2.0.0"
authors = ["Andrea Simeoni <andreasimeoni84@gmail.com>"]
edition = "2021"

[dev-dependencies]
ethers = { path = "../..", version = "2.0.0" }
eyre = "0.6"
tokio = { version = "1.18", features = ["full"] }
